# Generated by Django 3.0.4 on 2020-03-25 08:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default=' ', max_length=100)),
                ('user_img', models.ImageField(upload_to='Images/user')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('user_password', models.CharField(max_length=50)),
                ('user_phone', models.CharField(default='01', max_length=11, validators=[django.core.validators.RegexValidator(regex='^[+-]?[0-9]+$')])),
                ('user_country', models.CharField(max_length=100)),
                ('user_fb', models.URLField(default=None)),
                ('user_birthday', models.DateField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
