# Generated by Django 3.0.4 on 2020-03-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200325_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_birthday',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_fb',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_img',
            field=models.CharField(max_length=100),
        ),
    ]
