# Generated by Django 3.0.4 on 2020-03-30 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200330_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_phone',
            field=models.CharField(default=None, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^[+-]?[0-9]+$')]),
        ),
    ]
